export const t_followed_zones = 'Followed Zones'
export const t_time_zone_country = 'Time Zone Countries'
export const t_current_time = 'current time:'
export const t_follow = 'follow'
export const t_search_for_country = 'US/Aleutian'